# Generated by Django 3.1.8 on 2021-04-22 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Djangotest',
            fields=[
                ('userkey', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.CharField(max_length=20)),
                ('userpwd', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Djangotest',
                'managed': False,
            },
        ),
    ]
