# Generated by Django 3.1.8 on 2021-04-22 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBConnect', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='djangotest',
            options={'managed': True},
        ),
    ]
