# Generated by Django 3.1.8 on 2021-04-27 07:17

import DBConnect
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBConnect', '0003_auto_20210422_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_save_name', models.FileField(upload_to=DBConnect.file_upload_path_for_db)),
                ('file_origin_name', models.CharField(max_length=100)),
                ('file_path', models.CharField(max_length=100)),
                ('file_ext', models.CharField(max_length=10)),
                ('is_img', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'file_box',
            },
        ),
    ]
