# Generated by Django 3.1.8 on 2021-04-27 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBConnect', '0004_filemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileModel',
        ),
    ]
